# ItemInstanceResource.gd
# For unique/per-instance inventory items (artifacts, weapons, equipped gear, quest items).
# References a base ItemResource and holds instance-specific data.
# Place at res://scripts/data/item_instance_resource.gd

extends Resource
class_name ItemInstanceResource

@export var item_resource: ItemResource # Reference to the base item definition

# --- Instance-specific data (expand as needed) ---
@export_category("Instance Data")
@export var unique_id: String = "" # For tracking, if needed (optional: autogenerated elsewhere)
@export var custom_name: String = "" # Player-renamable, or for legendary items
@export var durability: int = -1 # Only relevant for some item types (-1 for items without durability)
@export var owner_id: int = 0 # If needed for ownership tracking (character ID)
@export var acquired_time: int = 0 # Game tick/time acquired

@export var custom_data: Dictionary = {} # For modding, quests, etc

# --- Utility functions ---
func get_display_name() -> String:
	return custom_name if custom_name != "" else (item_resource.display_name if item_resource else "")

func get_summary() -> String:
	return "%s | Durability: %d | Owner: %d" % [
		get_display_name(),
		durability,
		owner_id
	]

# --- How & Where to Use ---
# 1. Place at res://scripts/data/item_instance_resource.gd
# 2. Use for all non-stackable items in inventory (weapons, artifacts, quest items, etc).
# 3. Instantiate, set .item_resource to the base definition, fill custom fields as needed.
# 4. Inventory: for stackables, use {item_resource, quantity}; for uniques use ItemInstanceResource.
